name: deep-frugal-three
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.10
  - ipykernel 
  - ipywidgets
  - jax
  - matplotlib
  - ruff
  - equinox
  - econml
  - optax
  - pre-commit
  - r-base=4.2
  - rpy2=3.5
  - notebook
  - distrax
  - seaborn
  - pip
  - scikit-learn
  - wandb
  - pip:
    # - pre-commit
    # - flowjax
    - torch
    - zepid
    - --editable ./flowjax/ # using version v12.2.0
    - --editable ./torch-two-sample/
    - --editable ./


