name: deep-frugal-three
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.10
  - ipykernel 
  - ipywidgets
  - jax
  - matplotlib
  - ruff
  - equinox
  - optax
  - pre-commit
  - rpy2
  - notebook
  - distrax
  - seaborn
  - pip
  - pip:
    # - pre-commit
    # - flowjax
    - --editable ./flowjax/
    - --editable ./
