name: deep-frugal
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.8
  - ipykernel 
  - ipywidgets
  - jax
  - matplotlib
  - ruff
  - pip:
    - --editable ./
  # - pip:
  #   - some-package==1.2.3  # Example PyPI package
  #   - another-package