name: deep-frugal
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.8
  - ipykernel 
  - ipywidgets
  - jax
  - matplotlib
  - ruff
  - equinox
  - optax
  - pre-commit
  - notebook
  - distrax
  - seaborn
  - pip
  - pip:
    # - pre-commit
    - flowjax
    - --editable ./
