name: frugal-flows
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.10
  - ipykernel 
  - ipywidgets
  - jax=0.4.35
  - jaxlib=0.4.35
  - matplotlib
  - ruff
  - equinox=0.11.10
  - econml
  - optax
  - pre-commit
  - r-base # =4.2
  - rpy2 # =3.5
  - notebook
  - distrax
  - seaborn
  - pip
  - scikit-learn
  - wandb
  - pip:
    # - pre-commit
    # - flowjax
    # - torch  # removed: no macOS x86_64 wheels after PyTorch 2.3
    - zepid
    - flowjax==12.2.0
    # - --editable ./flowjax/ # using version v12.2.0
    # - --editable ./torch-two-sample/
    - --editable ./


