"""Margin pixel order test (margin_order_8x8.sh; 2026-10-02): fixed raster order (mfix) vs the default
shuffled margin, 8x8, all ten digits, E1/E2 x datasets 1-3 x fit seeds {k, 1001-1004}.

Each mfix fit is paired with the grid fit that has the same preset, dataset (assignment seed) and fit seed;
the two differ only in the margin's pixel order. Per fit: effect-map error (mean |estimate - true ATE| over
the 64 pixels), held-out margin and copula negative log likelihood (per row, lower is better), best epoch.
Per dataset: the same error and the leftover slope (slope of the error map on the confounding map) for the
5-fit average. Paired differences (mfix - shuffled): mean (standard error) over the 15 fits per preset,
or over the 3 datasets for the 5-fit average.
Writes runs/exp_ate_recovery/analysis/margin_order_8x8.{md,csv}.
"""
import glob
import json
import os
import re
import sys

import numpy as np
import pandas as pd

MM = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
sys.path.insert(0, MM)
import dataset_store as DS  # noqa: E402

OUT = os.path.join(MM, "runs", "exp_ate_recovery", "analysis")
PAT = re.compile(r"ff_(e[12])_flexcont_sa(\d+)_lr0\.001_copw16(_mfix)?_k64_s(\d+)_d0-9_[0-9a-f]{6}")

runs = {}
for d in glob.glob(os.path.join(MM, "runs", "exp_ate_recovery", "*_d0-9_*/")):
    if not (os.path.exists(d + "metrics.json") and os.path.exists(d + "model.eqx")):
        continue
    rec = json.load(open(d + "config.json"))
    m = PAT.fullmatch(rec.get("wandb_name", ""))
    if not m or int(m.group(2)) > 3:
        continue
    order = "fixed" if m.group(3) else "shuffled"
    assert rec["config"].get("margin_order", "shuffled") == order, d      # name and config agree
    runs[(m.group(1).upper(), int(m.group(2)), int(m.group(4)), order)] = d

rows, avg = [], []
for (p, k, s, order), d in runs.items():
    if order != "fixed" or (p, k, s, "shuffled") not in runs:
        continue
    for o in ("shuffled", "fixed"):
        r = runs[(p, k, s, o)]
        met = json.load(open(r + "metrics.json"))
        a = DS.run_arrays(r)
        tau, ate = np.asarray(a["tau_hat"]), np.asarray(a["ATE"])
        rows.append({"preset": p, "dataset": k, "seed": s, "order": o, "mae": np.abs(tau - ate).mean(),
                     "val_margin_nll": met.get("val_margin_nll"), "val_copula_nll": met.get("val_copula_nll"),
                     "best_epoch": met.get("best_epoch"), "termination": met.get("termination"), "_tau": tau})
x = pd.DataFrame(rows)
if x.empty:
    print("no paired runs yet"); sys.exit(0)

se = lambda s: s.std(ddof=1) / np.sqrt(len(s)) if len(s) > 1 else np.nan  # noqa: E731
for (p, k, o), g in x.groupby(["preset", "dataset", "order"]):
    if len(g) != 5:
        continue
    a = DS.run_arrays(runs[(p, k, g.seed.iloc[0], o)])
    T = a["X"][:, 0].astype(bool)
    ate = np.asarray(a["ATE"])
    imb = a["Y"][T].mean(0) - a["Y"][~T].mean(0) - ate
    err = np.mean(np.stack(g._tau), 0) - ate
    avg.append({"preset": p, "dataset": k, "order": o, "avg5_mae": np.abs(err).mean(),
                "avg5_slope": np.polyfit(imb, err, 1)[0]})
v = pd.DataFrame(avg)

summary = []
for p in sorted(x.preset.unique()):
    w = x[x.preset == p].pivot_table(index=["dataset", "seed"], columns="order",
                                     values=["mae", "val_margin_nll", "val_copula_nll", "best_epoch"])
    wa = v[v.preset == p].pivot_table(index="dataset", columns="order", values=["avg5_mae", "avg5_slope"])
    row = {"preset": p, "fits paired": len(w), "datasets paired": len(wa)}
    for c in ("mae", "val_margin_nll", "val_copula_nll", "best_epoch"):
        dd = w[c]["fixed"] - w[c]["shuffled"]
        row[c] = f"{w[c]['shuffled'].mean():.4f} -> {w[c]['fixed'].mean():.4f}  diff {dd.mean():+.4f} ({se(dd):.4f})"
    for c in ("avg5_mae", "avg5_slope"):
        dd = wa[c]["fixed"] - wa[c]["shuffled"]
        row[c] = f"{wa[c]['shuffled'].mean():.4f} -> {wa[c]['fixed'].mean():.4f}  diff {dd.mean():+.4f} ({se(dd):.4f})"
    summary.append(row)
summary = pd.DataFrame(summary)
term = x.groupby(["preset", "order"]).termination.value_counts().rename("fits").reset_index()

os.makedirs(OUT, exist_ok=True)
x.drop(columns="_tau").to_csv(os.path.join(OUT, "margin_order_8x8.csv"), index=False)
with open(os.path.join(OUT, "margin_order_8x8.md"), "w") as f:
    f.write("# Margin pixel order: shuffled (default) -> fixed (mfix), 8x8 all digits\n\n"
            "Generated by analyse_margin_order_8x8.py; see its docstring. Each cell: shuffled mean -> fixed mean, "
            "paired difference fixed - shuffled (standard error).\n\n" + summary.to_markdown(index=False)
            + "\n\n## How training ended\n\n" + term.to_markdown(index=False) + "\n")
pd.set_option("display.width", 250); pd.set_option("display.max_colwidth", 80)
print(summary.T.to_string()); print(); print(term.to_string(index=False))
print(f"\nwritten: {os.path.join(OUT, 'margin_order_8x8.md')}")
